<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
</head>
<body>

<?php require_once CONFIGS['viewPathDir'] . "/components/header.php" ?>

<?php require_once CONFIGS['viewPathDir'] . "/components/navigation.php" ?>

<main>
    <h1>
        Profile
        <small>[<a href="/profile/edit">edit</a>]</small>
    </h1>

    <?php require_once CONFIGS['viewPathDir'] . "/components/message.php" ?>

    <h2><?=$currentUser['name']?></h2>
    <p><?=$currentUser['description']?></p>

    <?php if (isset($photo)) : ?>
        <img src="<?=$photo?>" alt="<?=$currentUser['name']?>" width="300px"><br><br>
    <?php endif; ?>

</main>

<?php require_once CONFIGS['viewPathDir'] . "/components/footer.php" ?>

</body>
</html>