<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>

<?php require_once "components/header.php" ?>

<?php require_once "components/navigation.php" ?>

<main>
    <h1>Index</h1>

    <?php require_once "components/message.php" ?>

    <p>Hi! This is my home work in <a href="https://education.nixsolutions.com/">online NIX education</a>.</p>
</main>

<?php require_once "components/footer.php" ?>

</body>
</html>