<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Posts</title>
</head>
<body>

<?php require_once CONFIGS['viewPathDir'] . "/components/header.php" ?>

<?php require_once CONFIGS['viewPathDir'] . "/components/navigation.php" ?>

<main>
    <h1>Posts</h1>

    <?php if (isset($posts) && is_array($posts)) : ?>
        <ul>

        <?php foreach ($posts as $post) : ?>
        <li>
            <a href="#"><?=$post['title']?></a><br>
            <p><?=$post['text']?></p>
        </li>

        <?php endforeach; ?>

        </ul>

    <?php else : ?>
    <p>Posts not found.</p>

    <?php endif; ?>


</main>

<?php require_once CONFIGS['viewPathDir'] . "/components/footer.php" ?>

</body>
</html>