<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
</head>
<body>

<?php require_once "components/header.php" ?>

<?php require_once "components/navigation.php" ?>

<main>
    <h1>Registration</h1>

    <?php require_once "components/message.php" ?>

    <form method="post" action="/registration" style="display: inline-block">
        <fieldset>
            <label>
                Login:<br>
                <input name="login" type="text" required>
            </label>
            <br><br>
            <label>
                Password:<br>
                <input name="password" type="password" required>
            </label>
            <br><br>
            <input type="submit" name="submit" value="Signup">
        </fieldset>
    </form>
</main>

<?php require_once "components/footer.php" ?>

</body>
</html>